### ISSUE TITLE
Example doesn't bind any controllers

### ISSUE THREAD

**Issue by Banashek** [typeorm/typeorm-routing-controllers-extensions#5]
Not sure if this is intended, but the example [here](https://github.com/typeorm/typeorm-routing-controllers-extensions/blob/master/sample/sample1-simple-usage/app.ts#L23) calls createApplication without binding any controllers. 

Is it supposed to work purely off of reading the entites defined in `createConnection`?

for anyone wondering changing

```ts
createExpressServer().listen(3000);
```

to 

```ts

createExpressServer({
    controllers: [
        PostController
    ]
}).listen(3000);
```

will do the trick (along with the appropriate import at the top

**Comment by pleerock** [comment]
Yeah probably you are right. Can you create PR with this change?

**Comment by Banashek** [comment]
Sure

Btw awesome work you're doing with the set of typescript libraries you manage. You've made some really cool stuff.
